[package]
edition = "2021"
name = "cns-rust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
regex = "1"
tokio = {version = "1", features = ["full"]}

[profile.dev]
codegen-units = 256
opt-level = 0

[profile.release]
codegen-units = 16 
debug = false 
debug-assertions = false 
incremental = false 
lto = 'fat' 
opt-level = 'z' 
overflow-checks = false 
panic = 'unwind' 
rpath = false 
split-debuginfo = '...' # Platform-specific.
strip = true
